// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txenztnfqohkqwegodan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZW56dG5mcW9oa3F3ZWdvZGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzA2MzcsImV4cCI6MjA2MTg0NjYzN30.M-12sTgIvnunlYuK8wR7wYFu0NuxHnm8aaClaLmVOmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);